#!/usr/bin/env python3

import colors as c
import random

sides = []

sides.append('''
  -------
 |       |
 |   o   |
 |       |
  -------
''')

sides.append('''
  -------
 |     o |
 |       |
 |o      |
  -------
''')

sides.append('''
  -------
 |     o |
 |  o    |
 |o      |
  -------
''')

sides.append('''
  -------
 |o    o |
 |       |
 |o    o |
  -------
''')

sides.append('''
  -------
 |o    o |
 |   o   |
 |o    o |
  -------
''')

sides.append('''
  -------
 | o   o |
 | o   o |
 | o   o |
  -------
''')

num = 1
while True:
    print(c.clear, end="")
    for count in range(num):
    side = random.choice(sides) 
    print(c.clear + c.random_color() + side + c.reset)
    input()
